# Generated by Django 4.2.1 on 2023-05-07 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.CharField(
                        choices=[
                            ("bp", "Blood Pressure"),
                            ("hw", "Height/Weight in m/Kg"),
                            ("heartrate", "Heart Rate in bpm"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "exercise",
                    models.CharField(
                        choices=[
                            ("no", "No Exercise"),
                            ("low", "Low Intensity"),
                            ("mid", "Moderate Workout < 1 hour "),
                            ("high", "High Intensity Workout"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data_value", models.CharField(max_length=30)),
                ("date_time", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
