# Generated by Django 4.2.1 on 2023-05-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataApp", "0002_rename_data_healthdata_health_data_healthdata_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthdata",
            name="date_time",
            field=models.CharField(max_length=30),
        ),
    ]
