# Generated by Django 4.2.1 on 2023-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataApp", "0003_calculation_data_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculation",
            name="date_time",
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
