# Generated by Django 4.2.1 on 2023-05-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataApp", "0004_alter_healthdata_health_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthdata",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
