# Generated by Django 4.2.1 on 2023-05-10 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dataApp", "0005_healthdata_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "health_data",
                    models.CharField(
                        choices=[
                            ("bmi", "BMI Calculator"),
                            ("body fat", "Body Fat Calculator (needs BMI)"),
                            ("ideal weight in kg", "Ideal Weight Calculator in Kg"),
                            ("calorie", "Calorie Intake Calculator"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
